wrk.method = "GET"
wrk.path = "/echo_headers"
wrk.headers["Content-Type"] = "application/json"
wrk.headers["User-Agent"] = "wrk-benchmark/1.0"
wrk.headers["Accept"] = "application/json"
wrk.headers["Accept-Encoding"] = "gzip, deflate"
wrk.headers["Accept-Language"] = "en-US,en;q=0.9"
wrk.headers["Authorization"] = "Bearer test_token_1234567890"
wrk.headers["Cache-Control"] = "no-cache"
wrk.headers["X-Request-ID"] = "req_test_123"
wrk.headers["X-API-Key"] = "sk_test_key"
wrk.headers["Origin"] = "https://example.com"
