[package]
name = "gears"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[features]
android=[]
ios=[]

[dependencies]
include_dir = "0.7.4"
jni = "0.21.1"
mlua = { version = "0.9.9", features = ["lua54", "vendored"] }

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
cbindgen = "0.20"
