[target.aarch64-linux-android]
ar = "/Users/thalesgelinger/Library/Android/sdk/ndk/29.0.13113456/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
linker = "/Users/thalesgelinger/Library/Android/sdk/ndk/29.0.13113456/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android28-clang"
