[package]
name = "rover"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
toml = "0.7.2"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
notify = "6.1.1"
